# This file was generated by GoReleaser. DO NOT EDIT.
cask "vincent" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "d2d4ecd528f79f77ec3fd0cf85c6ea64585d96323c78995bed9eff43bf616b03"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "d13eefa2e6581554faaa22f18648c2205e36ab0e2ac049bce37072cc07e3f796"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5d07863e5a4f80e7702960d56799a82b77ff284f1007985fcdb036cc98d88323"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "dc9a1129364811875d02e339bcdfe306d8a10d4f116508cabc9b06e93b8f2119"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  name "vincent"
  desc "Vendor-independent control plane for executing native agent tooling"
  homepage "https://github.com/lezli01/vincent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vincent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vincent"]
    end
  end

  uninstall launchctl: [
      "dev.lezli01.vincent",
    ]

  zap trash: [
      "~/Library/Application Support/vincent",
      "~/Library/LaunchAgents/dev.lezli01.vincent.plist",
    ]

  caveats <<~EOS
    vincent runs coding agents FULL-AUTO by default: an agent can run
    arbitrary commands as you. Per-task git worktrees isolate collisions
    between tasks, not privileges. See the README's security section.

    Start the daemon in the background and keep it across reboots with:
      vincent service install
  EOS
end
