# This file was generated by GoReleaser. DO NOT EDIT.
cask "vincent" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "de0abe8487f22af46bf6d6cf804fb72dbbc037d3446b5b6cb4a1b732cb3f1c2b"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "a595a8da30989f5dae2020897a65bc4752ddde662896bcff30e07c03ff8a70d1"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a5850b015d5eac642b35f9047ea9af2b7cadb4108f5ee6774b17b4123a2327d"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "a6a675f13a15caf85def5857ed2af56f632da0849907eadb501595a43c56cd1e"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  name "vincent"
  desc "Vendor-independent control plane for executing native agent tooling"
  homepage "https://github.com/lezli01/vincent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vincent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vincent"]
    end
  end

  uninstall launchctl: [
      "dev.lezli01.vincent",
    ]

  zap trash: [
      "~/Library/Application Support/vincent",
      "~/Library/LaunchAgents/dev.lezli01.vincent.plist",
    ]

  caveats <<~EOS
    vincent runs coding agents FULL-AUTO by default: an agent can run
    arbitrary commands as you. Per-task git worktrees isolate collisions
    between tasks, not privileges. See the README's security section.

    Start the daemon in the background and keep it across reboots with:
      vincent service install
  EOS
end
