# This file was generated by GoReleaser. DO NOT EDIT.
cask "vincent" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "7bcb36a4cc25d62d100632f2b561412bb211cd3ee882cd8f088e68fb33fb58dc"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "2e47081e381b2e213bce60ac48747c6266f9130881d1619d10c2977c094f9c66"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  on_linux do
    on_intel do
      sha256 "32fe114b0bd25d7e648a90975610f7e5b40b0836b523a4c32b57b0017cf1f67f"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_amd64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
    on_arm do
      sha256 "be49e5c1bad28d8c7f02fb83f71898630493f9f68ca55dffeb1c7a94c9df3f54"
      url "https://github.com/lezli01/vincent/releases/download/v#{version}/vincent_#{version}_linux_arm64.tar.gz",
        verified: "github.com/lezli01/vincent/"
    end
  end

  name "vincent"
  desc "Vendor-independent control plane for executing native agent tooling"
  homepage "https://github.com/lezli01/vincent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vincent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vincent"]
    end
  end

  uninstall launchctl: [
      "dev.lezli01.vincent",
    ]

  zap trash: [
      "~/Library/Application Support/vincent",
      "~/Library/LaunchAgents/dev.lezli01.vincent.plist",
    ]

  caveats <<~EOS
    vincent runs coding agents FULL-AUTO by default: an agent can run
    arbitrary commands as you. Per-task git worktrees isolate collisions
    between tasks, not privileges. See the README's security section.

    Start the daemon in the background and keep it across reboots with:
      vincent service install
  EOS
end
